import {
	MAX_PASSWORD_SIZE,
	MIN_PASSWORD_SIZE,
	PASSWORD_CONFIRM_VALIDATION,
	PASSWORD_CONFIRM_VALIDATION_MESSAGE,
	PASSWORD_LOWERCASE,
	PASSWORD_LOWERCASE_MESSAGE,
	PASSWORD_NUMBER,
	PASSWORD_NUMBER_MESSAGE,
	PASSWORD_UPPERCASE,
	PASSWORD_UPPERCASE_MESSAGE
} from '$lib/features/user-management/config/passwordValidators'
import { z } from 'zod'

export const signupSchema = z
	.object({
		password: z
			.string()
			.min(MIN_PASSWORD_SIZE)
			.max(MAX_PASSWORD_SIZE)
			.refine(PASSWORD_UPPERCASE, PASSWORD_UPPERCASE_MESSAGE)
			.refine(PASSWORD_LOWERCASE, PASSWORD_LOWERCASE_MESSAGE)
			.refine(PASSWORD_NUMBER, PASSWORD_NUMBER_MESSAGE),
		confirmPassword: z.string(),
		email: z.string().email()
	})
	.refine(PASSWORD_CONFIRM_VALIDATION, PASSWORD_CONFIRM_VALIDATION_MESSAGE)
